name: build
on:
  push:
    paths:
      - 'common/src/main/java/**'
      - 'fabric/src/main/java/**'
      - 'neoforge/src/main/java/**'
      - '**/gradle.properties'
      - '**/settings.gradle'
      - '**/build.gradle'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Neoforge JAR to artifacts
        uses: actions/upload-artifact@v7
        with:
            archive: false
            retention-days: 90
            path: ./neoforge/build/libs/*[^-sources].jar

      - name: Upload Fabric JAR to artifacts
        uses: actions/upload-artifact@v7
        with:
            archive: false
            retention-days: 90
            path: ./fabric/build/libs/*[^-sources].jar
